package com.chicex.PictureCloud.Dao.mappers;

import com.chicex.PictureCloud.Objects.ImageInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface ImageInfoMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_images
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String imagekey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_images
     *
     * @mbggenerated
     */
    int insert(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_images
     *
     * @mbggenerated
     */
    int insertSelective(ImageInfo record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_images
     *
     * @mbggenerated
     */
    ImageInfo selectByPrimaryKey(String imagekey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ImageInfo record);

    List<ImageInfo> getAllImages();
}