package com.chicex.PictureCloud.Objects;

import com.chicex.PictureCloud.Utils.Utils;
import org.apache.commons.codec.digest.DigestUtils;

import javax.persistence.Id;
import javax.persistence.Table;
import java.util.*;

@Table(name = "imagesTable")
public class ImageInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_images.imageKey
     *
     * @mbggenerated
     */
    @Id
    private String imagekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_images.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_images.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_images.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_images.MD5
     *
     * @mbggenerated
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_images.userKey
     *
     * @mbggenerated
     */
    private String userkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_images.extraInfo
     *
     * @mbggenerated
     */
    private String extrainfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_images.Date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_images.imageKey
     *
     * @return the value of tb_images.imageKey
     *
     * @mbggenerated
     */
    public String getImagekey() {
        return imagekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_images.imageKey
     *
     * @param imagekey the value for tb_images.imageKey
     *
     * @mbggenerated
     */
    public void setImagekey(String imagekey) {
        this.imagekey = imagekey == null ? null : imagekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_images.name
     *
     * @return the value of tb_images.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_images.name
     *
     * @param name the value for tb_images.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_images.type
     *
     * @return the value of tb_images.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_images.type
     *
     * @param type the value for tb_images.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_images.path
     *
     * @return the value of tb_images.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_images.path
     *
     * @param path the value for tb_images.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_images.MD5
     *
     * @return the value of tb_images.MD5
     *
     * @mbggenerated
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_images.MD5
     *
     * @param md5 the value for tb_images.MD5
     *
     * @mbggenerated
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_images.userKey
     *
     * @return the value of tb_images.userKey
     *
     * @mbggenerated
     */
    public String getUserkey() {
        return userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_images.userKey
     *
     * @param userkey the value for tb_images.userKey
     *
     * @mbggenerated
     */
    public void setUserkey(String userkey) {
        this.userkey = userkey == null ? null : userkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_images.extraInfo
     *
     * @return the value of tb_images.extraInfo
     *
     * @mbggenerated
     */
    public String getExtrainfo() {
        return extrainfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_images.extraInfo
     *
     * @param extrainfo the value for tb_images.extraInfo
     *
     * @mbggenerated
     */
    public void setExtrainfo(String extrainfo) {
        this.extrainfo = extrainfo == null ? null : extrainfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_images.Date
     *
     * @return the value of tb_images.Date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_images.Date
     *
     * @param date the value for tb_images.Date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }


    public String createKey(){
        //String bf;
        return Utils.bytesToHexString(DigestUtils.sha1(this.getName()+new Random().nextInt(1000)));
    }

    public static List<String> Types(){
        List<String> list = new ArrayList<String>();
        list.add("jpg");
        list.add("jpeg");
        list.add("png");
        list.add("gif");
        list.add("JPG");
        list.add("JPEG");
        list.add("PNG");
        list.add("GIF");
        return list;
    }

    public static boolean matchType(String type){
        Iterator i = ImageInfo.Types().iterator();
        while (i.hasNext()){
            if (i.next().equals(type)){
                return true;
            }
        }
        return false;//Type  Error
    }


    public static long IMAGE_MAX_SIZE = 1048576000 ;//10mb
}